on:
  push:
    branches:
      - main
    paths:
      - "src/package/index.html"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: calitaz/discordpy-osrs
          path: discordpy-osrs
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Pull-Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: "[AUTO] - Update `index.html`"
          pr_body: ":crown: *Autocomplete PR*"
          pr_label: "auto-pr"
          pr_draft: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
