on:
  pull_request:
    branches:
      - main
    paths:
      - "src/package/**"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: pull-request
        uses: repo-sync/pull-request@v2
          with:
            destination_branch: "main"                        # If blank, default: master
            pr_title: "Pulling ${{ github.ref }} into main" # Title of pull request
            pr_template: ".github/PULL_REQUEST_TEMPLATE/second_template.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body
            pr_allow_empty: true                              # Creates pull request even if there are no changes