on:
  pull_request:
    branches:
      - main
    paths:
      - "src/package"

jobs:
  checklist_job:
    runs-on: ubuntu-latest
    name: Checklist job

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          toke: ${{ secrets.GH_ACTIONS_PAT }}
          fetch-depth: 0
      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v26.1
      - name: List all added files
        run: |
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            echo "$file was added"
          done
