on:
  pull_request:
    types:
      - opened
    branches:
      - main
    paths:
      - "src/package/**"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
