on:
  push:
    branches:
      - bleh
    paths:
      - "src/package/this.json"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Local Checkout
        uses: actions/checkout@v2
        with:
          repository: calitaz/tibia_discord_bot
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get File Content
      - id: set_var
        run: |
          content=`cat ./src/package/this.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=file::$content"
      - run: |
          echo "${{fromJson(steps.set_var.outputs.file).version}}"
      - name: Remote Repo Checkout
        uses: actions/checkout@v3
        with:
          repository: calitaz/tibia_discord_bot
          token: ${{ secrets.BOT }}
      - name: Make changes to pull request
        run: ${{steps.set_var.outputs.file}} > src/this.json
      - name: Pull-Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "[AUTO] - Update `index.html`"
          commit-message: Update index
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          body: |
            Update report
            - `index.html` was updated, please update your index.html
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          draft: true
          labels: |
            automated pr
          branch: auto-pr/update-index.html
          token: ${{ secrets.BOT }}
          base: main
