on:
  push:
    branches:
      - bleh
    paths:
      - "src/package/index.html"

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
    steps:
      # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff --name-only -r ${{ github.sha }} | xargs)"

  pull-request:
    runs-on: ubuntu-latest
    needs: changedfiles
    steps:
      - name: Remote Repo Checkout
        uses: actions/checkout@v3
        with:
          repository: calitaz/tibia_discord_bot
          token: ${{ secrets.BOT }}
      - name: Print
        run: |
          echo ${{needs.changedfiles.outputs.all}}
      - name: Make changes to pull request
        run: date +%s > report.txt
      # - name: Pull-Request
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     title: "[AUTO] - Update `index.html`"
      #     commit-message: Update index
      #     committer: GitHub <noreply@github.com>
      #     author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
      #     body: |
      #       Update report
      #       - `index.html` was updated, please update your index.html
      #       - Auto-generated by [create-pull-request][1]

      #       [1]: https://github.com/peter-evans/create-pull-request
      #     draft: true
      #     labels: |
      #       automated pr
      #     branch: auto-pr/update-index.html
      #     token: ${{ secrets.BOT }}
      #     base: main
